<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="MAIN" Id="{a7a322e6-ffe6-458a-a0c6-07c7acc5ec11}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	ENCODER : AXIS_REF;
	MOTOR	: AXIS_REF;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>